# -*- coding: utf-8 -*-
"""Range_Doppler_smoothing_KF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wgTN8RX6DBFdu6KLVV7rh5pF0i_ldPi
"""

import numpy as np
import pandas as pd


# -----------------------------
# User inputs
# -----------------------------
input_csv = "ManualClicks_RD - Copy_Mesa_2.csv"
output_csv = "Mesa_2_KF_Final_Rep_Removed.csv"

frame_col = "FrameIdx"
range_col = "Range_m"
velocity_col = "Velocity_ms"

frame_shift = 42
dt = 0.04

start_date_str = "2026-02-28"
start_time_str = "10:12:22.64"


# -----------------------------
# Noise settings
# -----------------------------
# Option A: use sensor specs directly
# Example:
# sigma_range = 0.50      # meters
# sigma_velocity = 0.20   # m/s

# Option B: estimate from data.
# These will be estimated later from low-motion samples.
estimate_R_from_data = True

# Acceleration process noise std dev.
# Larger = more responsive, smaller = smoother.
sigma_accel = 0.40   # m/s^2

# Mahalanobis gate threshold.
# For 2 measurement dimensions, 95% chi-square threshold = 5.99
# 99% threshold = 9.21
gate_threshold = 9.21


# -----------------------------
# Time helper
# -----------------------------
def make_timestamps(frame_index, frame_shift, dt, start_date_str, start_time_str):
    frame_zeroed = frame_index - frame_shift
    elapsed_s = frame_zeroed * dt

    start_datetime = pd.to_datetime(
        start_date_str + " " + start_time_str,
        format="%Y-%m-%d %H:%M:%S.%f"
    )

    timestamps = start_datetime + pd.to_timedelta(elapsed_s, unit="s")

    timestamps_formatted = (
        pd.Series(timestamps)
        .dt.strftime("%m/%d/%Y %H:%M:%S.%f")
        .str[:-3]
    )

    return frame_zeroed, elapsed_s, timestamps_formatted


# -----------------------------
# Estimate measurement noise R
# -----------------------------
def estimate_measurement_noise(range_meas, velocity_meas):
    """
    Estimate measurement noise from low-motion samples.

    This assumes regions with near-zero Doppler are approximately stationary.
    Adjust the threshold if needed.
    """

    stationary_mask = np.abs(velocity_meas) < 0.15

    if np.sum(stationary_mask) < 10:
        raise ValueError(
            "Not enough low-motion samples to estimate R. "
            "Use sensor specs instead by setting estimate_R_from_data=False."
        )

    sigma_range = np.std(range_meas[stationary_mask])
    sigma_velocity = np.std(velocity_meas[stationary_mask])

    # Avoid unrealistically tiny values
    sigma_range = max(sigma_range, 0.05)
    sigma_velocity = max(sigma_velocity, 0.05)

    R = np.diag([
        sigma_range**2,
        sigma_velocity**2
    ])

    return R, sigma_range, sigma_velocity


# -----------------------------
# Process noise Q from acceleration noise
# -----------------------------
def make_process_noise_Q(dt, sigma_accel):
    """
    Constant-acceleration process noise model.

    State:
        x = [range, velocity, acceleration]

    Acceleration is modeled as a random-walk-like disturbance.
    """

    G = np.array([
        [0.5 * dt**2],
        [dt],
        [1.0]
    ])

    Q = sigma_accel**2 * (G @ G.T)

    return Q


# -----------------------------
# Linear Kalman Filter
# State = [range, velocity, acceleration]
# Measurement = [range, velocity]
# -----------------------------
def run_kf(range_meas, velocity_meas, dt, Q, R, gate_threshold):
    F = np.array([
        [1.0, dt, 0.5 * dt**2],
        [0.0, 1.0, dt],
        [0.0, 0.0, 1.0]
    ])

    H = np.array([
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0]
    ])

    x = np.array([
        range_meas[0],
        velocity_meas[0],
        0.0
    ])

    P = np.diag([
        10.0,
        5.0,
        2.0
    ])

    I = np.eye(3)

    states = []
    mahalanobis_d2 = []
    accepted_update = []

    for r, v in zip(range_meas, velocity_meas):
        z = np.array([r, v])

        # Predict
        x = F @ x
        P = F @ P @ F.T + Q

        # Innovation
        y = z - H @ x
        S = H @ P @ H.T + R

        d2 = float(y.T @ np.linalg.inv(S) @ y)

        # Statistically justified gating
        if d2 < gate_threshold:
            K = P @ H.T @ np.linalg.inv(S)

            x = x + K @ y
            P = (I - K @ H) @ P

            accepted = True
        else:
            # Reject update, keep prediction
            accepted = False

        states.append(x.copy())
        mahalanobis_d2.append(d2)
        accepted_update.append(accepted)

    return np.array(states), np.array(mahalanobis_d2), np.array(accepted_update)


# -----------------------------
# Main pipeline
# -----------------------------
df = pd.read_csv(input_csv)

df.columns = df.columns.str.strip()
df = df.sort_values(frame_col).reset_index(drop=True)

range_meas = df[range_col].to_numpy(dtype=float)
velocity_meas = df[velocity_col].to_numpy(dtype=float)
frame_index = df[frame_col].to_numpy(dtype=int)

# Measurement noise R
if estimate_R_from_data:
    R, sigma_range, sigma_velocity = estimate_measurement_noise(
        range_meas,
        velocity_meas
    )

    print("Estimated measurement noise:")
    print(f"  sigma_range    = {sigma_range:.4f} m")
    print(f"  sigma_velocity = {sigma_velocity:.4f} m/s")

else:
    sigma_range = 0.50
    sigma_velocity = 0.20

    R = np.diag([
        sigma_range**2,
        sigma_velocity**2
    ])

# Process noise Q
Q = make_process_noise_Q(dt, sigma_accel)

print("R matrix:")
print(R)

print("Q matrix:")
print(Q)

states, d2, accepted_update = run_kf(
    range_meas=range_meas,
    velocity_meas=velocity_meas,
    dt=dt,
    Q=Q,
    R=R,
    gate_threshold=gate_threshold
)

frame_zeroed, elapsed_s, timestamps = make_timestamps(
    frame_index=frame_index,
    frame_shift=frame_shift,
    dt=dt,
    start_date_str=start_date_str,
    start_time_str=start_time_str
)

out = pd.DataFrame({
    "frame_index_original": frame_index,
    "frame_index_zeroed": frame_zeroed,
    "elapsed_time_s": elapsed_s,
    "timestamp": timestamps,

    "range_raw_m": range_meas,
    "velocity_raw_ms": velocity_meas,

    "range_kf_m": states[:, 0],
    "velocity_kf_ms": states[:, 1],
    "acceleration_kf_ms2": states[:, 2],

    "mahalanobis_d2": d2,
    "kf_update_accepted": accepted_update
})

out.to_csv(output_csv, index=False)

print(f"Saved: {output_csv}")

import numpy as np
import pandas as pd


# -----------------------------
# User inputs
# -----------------------------
input_csv = "First_Veh_raw.csv"
output_csv = "I10_FirstVeh_Smoothed.csv"

frame_col = "FrameIdx"
range_col = "Range_m"
velocity_col = "Velocity_ms"

frame_shift = 0
dt = 0.04

start_date_str = "2026-02-28"
start_time_str = "13:15:09.4"


# -----------------------------
# Noise settings
# -----------------------------
# Option A: use sensor specs directly
# Example:
# sigma_range = 0.50      # meters
# sigma_velocity = 0.20   # m/s

# Option B: estimate from data.
# These will be estimated later from low-motion samples.
estimate_R_from_data = True

# Acceleration process noise std dev.
# Larger = more responsive, smaller = smoother.
sigma_accel = 0.40   # m/s^2

# Mahalanobis gate threshold.
# For 2 measurement dimensions, 95% chi-square threshold = 5.99
# 99% threshold = 9.21
gate_threshold = 9.21


# -----------------------------
# Time helper
# -----------------------------
def make_timestamps(frame_index, frame_shift, dt, start_date_str, start_time_str):
    frame_zeroed = frame_index - frame_shift
    elapsed_s = frame_zeroed * dt

    start_datetime = pd.to_datetime(
        start_date_str + " " + start_time_str,
        format="%Y-%m-%d %H:%M:%S.%f"
    )

    timestamps = start_datetime + pd.to_timedelta(elapsed_s, unit="s")

    timestamps_formatted = (
        pd.Series(timestamps)
        .dt.strftime("%m/%d/%Y %H:%M:%S.%f")
        .str[:-3]
    )

    return frame_zeroed, elapsed_s, timestamps_formatted


# -----------------------------
# Estimate measurement noise R
# -----------------------------
def estimate_measurement_noise(range_meas, velocity_meas):
    """
    Estimate measurement noise from low-motion samples.

    This assumes regions with near-zero Doppler are approximately stationary.
    Adjust the threshold if needed.
    """

    stationary_mask = np.abs(velocity_meas) < 0.15

    if np.sum(stationary_mask) < 10:
        raise ValueError(
            "Not enough low-motion samples to estimate R. "
            "Use sensor specs instead by setting estimate_R_from_data=False."
        )

    sigma_range = np.std(range_meas[stationary_mask])
    sigma_velocity = np.std(velocity_meas[stationary_mask])

    # Avoid unrealistically tiny values
    sigma_range = max(sigma_range, 0.05)
    sigma_velocity = max(sigma_velocity, 0.05)

    R = np.diag([
        sigma_range**2,
        sigma_velocity**2
    ])

    return R, sigma_range, sigma_velocity


# -----------------------------
# Process noise Q from acceleration noise
# -----------------------------
def make_process_noise_Q(dt, sigma_accel):
    """
    Constant-acceleration process noise model.

    State:
        x = [range, velocity, acceleration]

    Acceleration is modeled as a random-walk-like disturbance.
    """

    G = np.array([
        [0.5 * dt**2],
        [dt],
        [1.0]
    ])

    Q = sigma_accel**2 * (G @ G.T)

    return Q


# -----------------------------
# Linear Kalman Filter
# State = [range, velocity, acceleration]
# Measurement = [range, velocity]
# -----------------------------
def run_kf(range_meas, velocity_meas, dt, Q, R, gate_threshold):
    F = np.array([
        [1.0, dt, 0.5 * dt**2],
        [0.0, 1.0, dt],
        [0.0, 0.0, 1.0]
    ])

    H = np.array([
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0]
    ])

    x = np.array([
        range_meas[0],
        velocity_meas[0],
        0.0
    ])

    P = np.diag([
        10.0,
        5.0,
        2.0
    ])

    I = np.eye(3)

    states = []
    mahalanobis_d2 = []
    accepted_update = []

    for r, v in zip(range_meas, velocity_meas):
        z = np.array([r, v])

        # Predict
        x = F @ x
        P = F @ P @ F.T + Q

        # Innovation
        y = z - H @ x
        S = H @ P @ H.T + R

        d2 = float(y.T @ np.linalg.inv(S) @ y)

        # Statistically justified gating
        if d2 < gate_threshold:
            K = P @ H.T @ np.linalg.inv(S)

            x = x + K @ y
            P = (I - K @ H) @ P

            accepted = True
        else:
            # Reject update, keep prediction
            accepted = False

        states.append(x.copy())
        mahalanobis_d2.append(d2)
        accepted_update.append(accepted)

    return np.array(states), np.array(mahalanobis_d2), np.array(accepted_update)


# -----------------------------
# Main pipeline
# -----------------------------
df = pd.read_csv(input_csv)

df.columns = df.columns.str.strip()
df = df.sort_values(frame_col).reset_index(drop=True)

range_meas = df[range_col].to_numpy(dtype=float)
velocity_meas = df[velocity_col].to_numpy(dtype=float)
frame_index = df[frame_col].to_numpy(dtype=int)

# Measurement noise R
if estimate_R_from_data:
    R, sigma_range, sigma_velocity = estimate_measurement_noise(
        range_meas,
        velocity_meas
    )

    print("Estimated measurement noise:")
    print(f"  sigma_range    = {sigma_range:.4f} m")
    print(f"  sigma_velocity = {sigma_velocity:.4f} m/s")

else:
    sigma_range = 0.50
    sigma_velocity = 0.20

    R = np.diag([
        sigma_range**2,
        sigma_velocity**2
    ])

# Process noise Q
Q = make_process_noise_Q(dt, sigma_accel)

print("R matrix:")
print(R)

print("Q matrix:")
print(Q)

states, d2, accepted_update = run_kf(
    range_meas=range_meas,
    velocity_meas=velocity_meas,
    dt=dt,
    Q=Q,
    R=R,
    gate_threshold=gate_threshold
)

frame_zeroed, elapsed_s, timestamps = make_timestamps(
    frame_index=frame_index,
    frame_shift=frame_shift,
    dt=dt,
    start_date_str=start_date_str,
    start_time_str=start_time_str
)

out = pd.DataFrame({
    "frame_index_original": frame_index,
    "frame_index_zeroed": frame_zeroed,
    "elapsed_time_s": elapsed_s,
    "timestamp": timestamps,

    "range_raw_m": range_meas,
    "velocity_raw_ms": velocity_meas,

    "range_kf_m": states[:, 0],
    "velocity_kf_ms": states[:, 1],
    "acceleration_kf_ms2": states[:, 2],

    "mahalanobis_d2": d2,
    "kf_update_accepted": accepted_update
})

out.to_csv(output_csv, index=False)

print(f"Saved: {output_csv}")

import numpy as np
import pandas as pd


# -----------------------------
# User inputs
# -----------------------------
input_csv = "Second_Veh_raw.csv"
output_csv = "I10_SecondVeh_Smoothed.csv"

frame_col = "FrameIdx"
range_col = "Range_m"
velocity_col = "Velocity_ms"

frame_shift = 2757
dt = 0.04

start_date_str = "2026-02-28"
start_time_str = "13:17:22.6"


# -----------------------------
# Noise settings
# -----------------------------
# Option A: use sensor specs directly
# Example:
# sigma_range = 0.50      # meters
# sigma_velocity = 0.20   # m/s

# Option B: estimate from data.
# These will be estimated later from low-motion samples.
estimate_R_from_data = True

# Acceleration process noise std dev.
# Larger = more responsive, smaller = smoother.
sigma_accel = 0.40   # m/s^2

# Mahalanobis gate threshold.
# For 2 measurement dimensions, 95% chi-square threshold = 5.99
# 99% threshold = 9.21
gate_threshold = 9.21


# -----------------------------
# Time helper
# -----------------------------
def make_timestamps(frame_index, frame_shift, dt, start_date_str, start_time_str):
    frame_zeroed = frame_index - frame_shift
    elapsed_s = frame_zeroed * dt

    start_datetime = pd.to_datetime(
        start_date_str + " " + start_time_str,
        format="%Y-%m-%d %H:%M:%S.%f"
    )

    timestamps = start_datetime + pd.to_timedelta(elapsed_s, unit="s")

    timestamps_formatted = (
        pd.Series(timestamps)
        .dt.strftime("%m/%d/%Y %H:%M:%S.%f")
        .str[:-3]
    )

    return frame_zeroed, elapsed_s, timestamps_formatted


# -----------------------------
# Estimate measurement noise R
# -----------------------------
def estimate_measurement_noise(range_meas, velocity_meas):
    """
    Estimate measurement noise from low-motion samples.

    This assumes regions with near-zero Doppler are approximately stationary.
    Adjust the threshold if needed.
    """

    stationary_mask = np.abs(velocity_meas) < 0.15

    if np.sum(stationary_mask) < 10:
        raise ValueError(
            "Not enough low-motion samples to estimate R. "
            "Use sensor specs instead by setting estimate_R_from_data=False."
        )

    sigma_range = np.std(range_meas[stationary_mask])
    sigma_velocity = np.std(velocity_meas[stationary_mask])

    # Avoid unrealistically tiny values
    sigma_range = max(sigma_range, 0.05)
    sigma_velocity = max(sigma_velocity, 0.05)

    R = np.diag([
        sigma_range**2,
        sigma_velocity**2
    ])

    return R, sigma_range, sigma_velocity


# -----------------------------
# Process noise Q from acceleration noise
# -----------------------------
def make_process_noise_Q(dt, sigma_accel):
    """
    Constant-acceleration process noise model.

    State:
        x = [range, velocity, acceleration]

    Acceleration is modeled as a random-walk-like disturbance.
    """

    G = np.array([
        [0.5 * dt**2],
        [dt],
        [1.0]
    ])

    Q = sigma_accel**2 * (G @ G.T)

    return Q


# -----------------------------
# Linear Kalman Filter
# State = [range, velocity, acceleration]
# Measurement = [range, velocity]
# -----------------------------
def run_kf(range_meas, velocity_meas, dt, Q, R, gate_threshold):
    F = np.array([
        [1.0, dt, 0.5 * dt**2],
        [0.0, 1.0, dt],
        [0.0, 0.0, 1.0]
    ])

    H = np.array([
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0]
    ])

    x = np.array([
        range_meas[0],
        velocity_meas[0],
        0.0
    ])

    P = np.diag([
        10.0,
        5.0,
        2.0
    ])

    I = np.eye(3)

    states = []
    mahalanobis_d2 = []
    accepted_update = []

    for r, v in zip(range_meas, velocity_meas):
        z = np.array([r, v])

        # Predict
        x = F @ x
        P = F @ P @ F.T + Q

        # Innovation
        y = z - H @ x
        S = H @ P @ H.T + R

        d2 = float(y.T @ np.linalg.inv(S) @ y)

        # Statistically justified gating
        if d2 < gate_threshold:
            K = P @ H.T @ np.linalg.inv(S)

            x = x + K @ y
            P = (I - K @ H) @ P

            accepted = True
        else:
            # Reject update, keep prediction
            accepted = False

        states.append(x.copy())
        mahalanobis_d2.append(d2)
        accepted_update.append(accepted)

    return np.array(states), np.array(mahalanobis_d2), np.array(accepted_update)


# -----------------------------
# Main pipeline
# -----------------------------
df = pd.read_csv(input_csv)

df.columns = df.columns.str.strip()
df = df.sort_values(frame_col).reset_index(drop=True)

range_meas = df[range_col].to_numpy(dtype=float)
velocity_meas = df[velocity_col].to_numpy(dtype=float)
frame_index = df[frame_col].to_numpy(dtype=int)

# Measurement noise R
if estimate_R_from_data:
    R, sigma_range, sigma_velocity = estimate_measurement_noise(
        range_meas,
        velocity_meas
    )

    print("Estimated measurement noise:")
    print(f"  sigma_range    = {sigma_range:.4f} m")
    print(f"  sigma_velocity = {sigma_velocity:.4f} m/s")

else:
    sigma_range = 0.50
    sigma_velocity = 0.20

    R = np.diag([
        sigma_range**2,
        sigma_velocity**2
    ])

# Process noise Q
Q = make_process_noise_Q(dt, sigma_accel)

print("R matrix:")
print(R)

print("Q matrix:")
print(Q)

states, d2, accepted_update = run_kf(
    range_meas=range_meas,
    velocity_meas=velocity_meas,
    dt=dt,
    Q=Q,
    R=R,
    gate_threshold=gate_threshold
)

frame_zeroed, elapsed_s, timestamps = make_timestamps(
    frame_index=frame_index,
    frame_shift=frame_shift,
    dt=dt,
    start_date_str=start_date_str,
    start_time_str=start_time_str
)

out = pd.DataFrame({
    "frame_index_original": frame_index,
    "frame_index_zeroed": frame_zeroed,
    "elapsed_time_s": elapsed_s,
    "timestamp": timestamps,

    "range_raw_m": range_meas,
    "velocity_raw_ms": velocity_meas,

    "range_kf_m": states[:, 0],
    "velocity_kf_ms": states[:, 1],
    "acceleration_kf_ms2": states[:, 2],

    "mahalanobis_d2": d2,
    "kf_update_accepted": accepted_update
})

out.to_csv(output_csv, index=False)

print(f"Saved: {output_csv}")

import numpy as np
import pandas as pd


# -----------------------------
# User inputs
# -----------------------------
input_csv = "Mesa8_raw.csv"
output_csv = "Mesa_8_KF_Final_Rep_Removed.csv"

frame_col = "FrameIdx"
range_col = "Range_m"
velocity_col = "Velocity_ms"

frame_shift = 657
dt = 0.04

start_date_str = "2026-03-22"
start_time_str = "12:53:20.24"


# -----------------------------
# Noise settings
# -----------------------------
# Option A: use sensor specs directly
# Example:
# sigma_range = 0.50      # meters
# sigma_velocity = 0.20   # m/s

# Option B: estimate from data.
# These will be estimated later from low-motion samples.
estimate_R_from_data = True

# Acceleration process noise std dev.
# Larger = more responsive, smaller = smoother.
sigma_accel = 0.40   # m/s^2

# Mahalanobis gate threshold.
# For 2 measurement dimensions, 95% chi-square threshold = 5.99
# 99% threshold = 9.21
gate_threshold = 9.21


# -----------------------------
# Time helper
# -----------------------------
def make_timestamps(frame_index, frame_shift, dt, start_date_str, start_time_str):
    frame_zeroed = frame_index - frame_shift
    elapsed_s = frame_zeroed * dt

    start_datetime = pd.to_datetime(
        start_date_str + " " + start_time_str,
        format="%Y-%m-%d %H:%M:%S.%f"
    )

    timestamps = start_datetime + pd.to_timedelta(elapsed_s, unit="s")

    timestamps_formatted = (
        pd.Series(timestamps)
        .dt.strftime("%m/%d/%Y %H:%M:%S.%f")
        .str[:-3]
    )

    return frame_zeroed, elapsed_s, timestamps_formatted


# -----------------------------
# Estimate measurement noise R
# -----------------------------
def estimate_measurement_noise(range_meas, velocity_meas):
    """
    Estimate measurement noise from low-motion samples.

    This assumes regions with near-zero Doppler are approximately stationary.
    Adjust the threshold if needed.
    """

    stationary_mask = np.abs(velocity_meas) < 0.15

    if np.sum(stationary_mask) < 10:
        raise ValueError(
            "Not enough low-motion samples to estimate R. "
            "Use sensor specs instead by setting estimate_R_from_data=False."
        )

    sigma_range = np.std(range_meas[stationary_mask])
    sigma_velocity = np.std(velocity_meas[stationary_mask])

    # Avoid unrealistically tiny values
    sigma_range = max(sigma_range, 0.05)
    sigma_velocity = max(sigma_velocity, 0.05)

    R = np.diag([
        sigma_range**2,
        sigma_velocity**2
    ])

    return R, sigma_range, sigma_velocity


# -----------------------------
# Process noise Q from acceleration noise
# -----------------------------
def make_process_noise_Q(dt, sigma_accel):
    """
    Constant-acceleration process noise model.

    State:
        x = [range, velocity, acceleration]

    Acceleration is modeled as a random-walk-like disturbance.
    """

    G = np.array([
        [0.5 * dt**2],
        [dt],
        [1.0]
    ])

    Q = sigma_accel**2 * (G @ G.T)

    return Q


# -----------------------------
# Linear Kalman Filter
# State = [range, velocity, acceleration]
# Measurement = [range, velocity]
# -----------------------------
def run_kf(range_meas, velocity_meas, dt, Q, R, gate_threshold):
    F = np.array([
        [1.0, dt, 0.5 * dt**2],
        [0.0, 1.0, dt],
        [0.0, 0.0, 1.0]
    ])

    H = np.array([
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0]
    ])

    x = np.array([
        range_meas[0],
        velocity_meas[0],
        0.0
    ])

    P = np.diag([
        10.0,
        5.0,
        2.0
    ])

    I = np.eye(3)

    states = []
    mahalanobis_d2 = []
    accepted_update = []

    for r, v in zip(range_meas, velocity_meas):
        z = np.array([r, v])

        # Predict
        x = F @ x
        P = F @ P @ F.T + Q

        # Innovation
        y = z - H @ x
        S = H @ P @ H.T + R

        d2 = float(y.T @ np.linalg.inv(S) @ y)

        # Statistically justified gating
        if d2 < gate_threshold:
            K = P @ H.T @ np.linalg.inv(S)

            x = x + K @ y
            P = (I - K @ H) @ P

            accepted = True
        else:
            # Reject update, keep prediction
            accepted = False

        states.append(x.copy())
        mahalanobis_d2.append(d2)
        accepted_update.append(accepted)

    return np.array(states), np.array(mahalanobis_d2), np.array(accepted_update)


# -----------------------------
# Main pipeline
# -----------------------------
df = pd.read_csv(input_csv)

df.columns = df.columns.str.strip()
df = df.sort_values(frame_col).reset_index(drop=True)

range_meas = df[range_col].to_numpy(dtype=float)
velocity_meas = df[velocity_col].to_numpy(dtype=float)
frame_index = df[frame_col].to_numpy(dtype=int)

# Measurement noise R
if estimate_R_from_data:
    R, sigma_range, sigma_velocity = estimate_measurement_noise(
        range_meas,
        velocity_meas
    )

    print("Estimated measurement noise:")
    print(f"  sigma_range    = {sigma_range:.4f} m")
    print(f"  sigma_velocity = {sigma_velocity:.4f} m/s")

else:
    sigma_range = 0.50
    sigma_velocity = 0.20

    R = np.diag([
        sigma_range**2,
        sigma_velocity**2
    ])

# Process noise Q
Q = make_process_noise_Q(dt, sigma_accel)

print("R matrix:")
print(R)

print("Q matrix:")
print(Q)

states, d2, accepted_update = run_kf(
    range_meas=range_meas,
    velocity_meas=velocity_meas,
    dt=dt,
    Q=Q,
    R=R,
    gate_threshold=gate_threshold
)

frame_zeroed, elapsed_s, timestamps = make_timestamps(
    frame_index=frame_index,
    frame_shift=frame_shift,
    dt=dt,
    start_date_str=start_date_str,
    start_time_str=start_time_str
)

out = pd.DataFrame({
    "frame_index_original": frame_index,
    "frame_index_zeroed": frame_zeroed,
    "elapsed_time_s": elapsed_s,
    "timestamp": timestamps,

    "range_raw_m": range_meas,
    "velocity_raw_ms": velocity_meas,

    "range_kf_m": states[:, 0],
    "velocity_kf_ms": states[:, 1],
    "acceleration_kf_ms2": states[:, 2],

    "mahalanobis_d2": d2,
    "kf_update_accepted": accepted_update
})

out.to_csv(output_csv, index=False)

print(f"Saved: {output_csv}")

# Kalman Filter-Based Smoother for FMCW Radar Range-Doppler Measurements
#
# Applies a linear Kalman filter to smooth raw per-frame range and velocity
# readings extracted interactively from Range-Doppler maps. The filter state
# comprises range, velocity, and acceleration. Measurement noise is estimated
# directly from low-motion frames; process noise is constructed under a
# constant-acceleration assumption. Mahalanobis distance gating rejects
# outlier measurements before each state update.

import numpy as np
import pandas as pd


# =============================================================================
# User Settings
# =============================================================================
input_csv    = "Mesa8_raw.csv"             # input CSV from the interactive click export
output_csv   = "Mesa_8_KF_Final_Rep_Removed.csv"  # output CSV with smoothed trajectories

frame_col    = "FrameIdx"                  # column name for frame index
range_col    = "Range_m"                   # column name for raw range (m)
velocity_col = "Velocity_ms"               # column name for raw velocity (m/s)

frame_shift  = 657                         # frame index offset to zero-align the timeline
dt           = 0.04                        # inter-frame interval (s); 25 Hz radar

start_date_str = "2026-03-22"              # recording date (YYYY-MM-DD)
start_time_str = "12:53:20.24"             # recording start time (HH:MM:SS.ss)

# -----------------------------------------------------------------------------
# Measurement noise covariance R
# Option A (estimate_R_from_data = True):
#   sigma_range and sigma_velocity are estimated from frames where the
#   observed Doppler is near zero (low-motion intervals).
# Option B (estimate_R_from_data = False):
#   Supply sigma_range and sigma_velocity directly from sensor specifications.
# -----------------------------------------------------------------------------
estimate_R_from_data = True                # True = data-driven; False = use sensor specs

# Used only when estimate_R_from_data = False
# sigma_range    = 0.50                    # range measurement noise std dev (m)
# sigma_velocity = 0.20                    # velocity measurement noise std dev (m/s)

# -----------------------------------------------------------------------------
# Process noise
# sigma_accel controls the expected std dev of unmodeled acceleration (m/s^2).
# Larger value -> more responsive to maneuvers; smaller value -> smoother output.
# -----------------------------------------------------------------------------
sigma_accel = 0.40                         # acceleration process noise std dev (m/s^2)

# -----------------------------------------------------------------------------
# Mahalanobis distance gating threshold (chi-square distribution, 2 DOF)
#   95th percentile: 5.99
#   99th percentile: 9.21  <-- used here
# Measurements whose squared Mahalanobis distance exceeds this threshold
# are rejected as outliers and the predicted state is retained instead.
# -----------------------------------------------------------------------------
gate_threshold = 9.21                      # chi-square gating threshold (2 DOF, 99%)


# =============================================================================
# Timestamp Generator
# =============================================================================
def make_timestamps(frame_index, frame_shift, dt, start_date_str, start_time_str):
    """
    Converts original frame indices to wall-clock timestamps.

    Parameters
    ----------
    frame_index    : array of original frame indices from the click export
    frame_shift    : integer offset to zero-align the frame timeline
    dt             : inter-frame interval (s)
    start_date_str : recording date string (YYYY-MM-DD)
    start_time_str : recording start time string (HH:MM:SS.ss)

    Returns
    -------
    frame_zeroed          : zero-aligned frame indices
    elapsed_s             : elapsed time from start (s)
    timestamps_formatted  : formatted wall-clock timestamps (MM/DD/YYYY HH:MM:SS.mmm)
    """
    frame_zeroed = frame_index - frame_shift          # shift frame index to start at zero
    elapsed_s    = frame_zeroed * dt                  # elapsed time from recording start (s)

    start_datetime = pd.to_datetime(
        start_date_str + " " + start_time_str,
        format="%Y-%m-%d %H:%M:%S.%f"
    )

    timestamps = start_datetime + pd.to_timedelta(elapsed_s, unit="s")

    timestamps_formatted = (
        pd.Series(timestamps)
        .dt.strftime("%m/%d/%Y %H:%M:%S.%f")
        .str[:-3]                                     # trim microseconds to milliseconds
    )

    return frame_zeroed, elapsed_s, timestamps_formatted


# =============================================================================
# Measurement Noise Estimator
# =============================================================================
def estimate_measurement_noise(range_meas, velocity_meas):
    """
    Estimates the measurement noise covariance R from low-motion frames.

    Frames where |velocity| < 0.15 m/s are treated as approximately stationary.
    The standard deviation of range and velocity readings across those frames
    is used as the respective noise standard deviations. A minimum floor of
    0.05 is applied to avoid unrealistically small values.

    Parameters
    ----------
    range_meas    : raw range measurements (m)
    velocity_meas : raw velocity measurements (m/s)

    Returns
    -------
    R              : 2x2 diagonal measurement noise covariance matrix
    sigma_range    : estimated range noise std dev (m)
    sigma_velocity : estimated velocity noise std dev (m/s)
    """
    stationary_mask = np.abs(velocity_meas) < 0.15   # low-motion frame selector

    if np.sum(stationary_mask) < 10:
        raise ValueError(
            "Not enough low-motion samples to estimate R. "
            "Set estimate_R_from_data=False and supply sensor specs instead."
        )

    sigma_range    = np.std(range_meas[stationary_mask])
    sigma_velocity = np.std(velocity_meas[stationary_mask])

    sigma_range    = max(sigma_range,    0.05)        # apply minimum floor
    sigma_velocity = max(sigma_velocity, 0.05)        # apply minimum floor

    R = np.diag([sigma_range**2, sigma_velocity**2])  # diagonal measurement noise covariance

    return R, sigma_range, sigma_velocity


# =============================================================================
# Process Noise Constructor
# =============================================================================
def make_process_noise_Q(dt, sigma_accel):
    """
    Constructs the process noise covariance Q under a constant-acceleration
    assumption (Singer model). Acceleration is treated as a zero-mean random
    disturbance with standard deviation sigma_accel.

    State vector: x = [range, velocity, acceleration]

    Parameters
    ----------
    dt          : inter-frame interval (s)
    sigma_accel : acceleration process noise std dev (m/s^2)

    Returns
    -------
    Q : 3x3 process noise covariance matrix
    """
    G = np.array([
        [0.5 * dt**2],   # range component of acceleration input
        [dt],            # velocity component of acceleration input
        [1.0]            # acceleration component
    ])

    Q = sigma_accel**2 * (G @ G.T)                   # process noise covariance

    return Q


# =============================================================================
# Linear Kalman Filter
# =============================================================================
def run_kf(range_meas, velocity_meas, dt, Q, R, gate_threshold):
    """
    Runs a linear Kalman filter with Mahalanobis distance gating.

    State  : x = [range (m), velocity (m/s), acceleration (m/s^2)]
    Measurement : z = [range (m), velocity (m/s)]

    At each frame:
      1. Predict: propagate state and covariance forward using F.
      2. Gate   : compute squared Mahalanobis distance d^2 of the new
                  measurement against the predicted state. Accept if
                  d^2 < gate_threshold; otherwise reject and coast.
      3. Update : if accepted, compute Kalman gain and update state
                  and covariance; if rejected, retain predicted state.

    Parameters
    ----------
    range_meas     : raw range measurements (m), length N
    velocity_meas  : raw velocity measurements (m/s), length N
    dt             : inter-frame interval (s)
    Q              : 3x3 process noise covariance
    R              : 2x2 measurement noise covariance
    gate_threshold : chi-square gating threshold

    Returns
    -------
    states          : (N, 3) array of filtered [range, velocity, acceleration]
    mahalanobis_d2  : (N,) array of squared Mahalanobis distances
    accepted_update : (N,) boolean array; True if measurement was accepted
    """

    # State transition matrix (constant-acceleration kinematics)
    F = np.array([
        [1.0, dt,  0.5 * dt**2],
        [0.0, 1.0, dt          ],
        [0.0, 0.0, 1.0         ]
    ])

    # Measurement matrix (observing range and velocity only)
    H = np.array([
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0]
    ])

    # Initialise state from first measurement; zero initial acceleration
    x = np.array([range_meas[0], velocity_meas[0], 0.0])

    # Initialise state covariance (large values reflect high initial uncertainty)
    P = np.diag([10.0, 5.0, 2.0])

    I = np.eye(3)                                     # identity matrix for covariance update

    states          = []
    mahalanobis_d2  = []
    accepted_update = []

    for r, v in zip(range_meas, velocity_meas):
        z = np.array([r, v])                          # measurement vector for this frame

        # --- Predict ---
        x = F @ x                                     # predicted state
        P = F @ P @ F.T + Q                           # predicted covariance

        # --- Innovation ---
        y = z - H @ x                                 # measurement residual (innovation)
        S = H @ P @ H.T + R                           # innovation covariance

        # --- Mahalanobis distance gating ---
        d2 = float(y.T @ np.linalg.inv(S) @ y)       # squared Mahalanobis distance

        if d2 < gate_threshold:
            # Measurement is consistent with prediction: perform update
            K = P @ H.T @ np.linalg.inv(S)           # Kalman gain
            x = x + K @ y                             # updated state
            P = (I - K @ H) @ P                       # updated covariance
            accepted = True
        else:
            # Measurement is an outlier: retain predicted state
            accepted = False

        states.append(x.copy())
        mahalanobis_d2.append(d2)
        accepted_update.append(accepted)

    return np.array(states), np.array(mahalanobis_d2), np.array(accepted_update)


# =============================================================================
# Main Pipeline
# =============================================================================
df = pd.read_csv(input_csv)
df.columns = df.columns.str.strip()
df = df.sort_values(frame_col).reset_index(drop=True)

range_meas    = df[range_col].to_numpy(dtype=float)   # raw range array (m)
velocity_meas = df[velocity_col].to_numpy(dtype=float) # raw velocity array (m/s)
frame_index   = df[frame_col].to_numpy(dtype=int)      # original frame indices

# --- Measurement noise covariance R ---
if estimate_R_from_data:
    R, sigma_range, sigma_velocity = estimate_measurement_noise(range_meas, velocity_meas)
    print(f"Estimated measurement noise:")
    print(f"  sigma_range    = {sigma_range:.4f} m")
    print(f"  sigma_velocity = {sigma_velocity:.4f} m/s")
else:
    sigma_range    = 0.50                              # range noise std dev (m) from sensor specs
    sigma_velocity = 0.20                              # velocity noise std dev (m/s) from sensor specs
    R = np.diag([sigma_range**2, sigma_velocity**2])

# --- Process noise covariance Q ---
Q = make_process_noise_Q(dt, sigma_accel)

print("R matrix:"); print(R)
print("Q matrix:"); print(Q)

# --- Run Kalman filter ---
states, d2, accepted_update = run_kf(
    range_meas=range_meas,
    velocity_meas=velocity_meas,
    dt=dt,
    Q=Q,
    R=R,
    gate_threshold=gate_threshold
)

# --- Generate timestamps ---
frame_zeroed, elapsed_s, timestamps = make_timestamps(
    frame_index=frame_index,
    frame_shift=frame_shift,
    dt=dt,
    start_date_str=start_date_str,
    start_time_str=start_time_str
)

# --- Assemble and save output ---
out = pd.DataFrame({
    "frame_index_original" : frame_index,              # original frame index from click export
    "frame_index_zeroed"   : frame_zeroed,             # zero-aligned frame index
    "elapsed_time_s"       : elapsed_s,                # elapsed time from recording start (s)
    "timestamp"            : timestamps,               # wall-clock timestamp

    "range_raw_m"          : range_meas,               # raw range from click export (m)
    "velocity_raw_ms"      : velocity_meas,            # raw velocity from click export (m/s)

    "range_kf_m"           : states[:, 0],             # Kalman-filtered range (m)
    "velocity_kf_ms"       : states[:, 1],             # Kalman-filtered velocity (m/s)
    "acceleration_kf_ms2"  : states[:, 2],             # Kalman-estimated acceleration (m/s^2)

    "mahalanobis_d2"       : d2,                       # squared Mahalanobis distance per frame
    "kf_update_accepted"   : accepted_update           # True if measurement was used for update
})

out.to_csv(output_csv, index=False)
print(f"Saved: {output_csv}")